spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: trading

exchange:
  url: "https://api.worldtradingdata.com/api/v1/forex"
  api-key: yy9MnkcNUwWizudg6DYMoF35tzlcNoyLNj5WWsNCTRfxkIBJ4ptw7rQdWqz8
